### ISSUE TITLE
Cannot access on default tabs

### ISSUE THREAD

**Issue by edgarasben** [alyssaxuu/omni#42] opened 2022-01-16 01:06 UTC
I cannot access Omni on default browser tab states like in an empty tab.

But I noticed my other browser extension shortcuts work, e.g. Notion:
![image](https://user-images.githubusercontent.com/725324/149643385-b21d5b52-6800-40d2-9585-50e34a5e27d5.png)

**Comment by yoroshikun** [comment] 2022-01-16 01:10
This is a restriction on how the current implementation is developed. Dupe of #28 #27 and #21 

Notion works because they are using the popup interface which is compatible with default tabs etc.

**Comment by alyssaxuu** [comment] 2022-01-16 10:02
Yeah, I don't really know what to do here. Here's a few options I am thinking about:

- If on the new tab page and trying to open Omni, open a new page that has Omni open automatically. Try to see if the new tab page can also be closed. This could work in theory, although unsure what page should be opened. Maybe a blank one (I could create a blank page within the extension for example), or bring the user to the homepage of their default search engine and inject it there?

- Create some sort of popup (same as Notion) so this way I could inform the user that Omni won't work there. It could be used to put all sorts of settings, although it would mean that Omni wouldn't open in one click by clicking on the toolbar icon anymore. This still doesn't solve the Command + K problem.

- Make the icon red / greyed out in the new tab page to show that it's disabled. This might not be clear enough to the user though, and it might look like it's broken.

What do you think would be the best approach?

**Comment by alyssaxuu** [comment] 2022-01-16 11:28
I ended up doing the #1 option. If you close Omni, it goes back to the page you were before. Better than nothing I think!

**Closed by alyssaxuu** 2022-01-16 11:28 UTC
Labels: question
