### ISSUE TITLE
Keybindings override

### ISSUE THREAD

**Issue by dadyarri** [alyssaxuu/omni#33] opened 2022-01-15 11:48 UTC
If current tab has actions on keyboard (like escape key in telegram web) it overrides action in Omni, and Omni does not closing

**Comment by sreechar** [comment] 2022-01-15 13:56
> If current tab has actions on keyboard (like escape key in telegram web) it overrides action in Omni, and Omni does not closing

Bro, just click outside the menu
It will exit

**Comment by dadyarri** [comment] 2022-01-15 15:28
> Bro, just click outside the menu
I know, but there should be way to do it without mouse in that case

**Comment by sreechar** [comment] 2022-01-16 01:54
> > Bro, just click outside the menu
> 
> I know, but there should be way to do it without mouse in that case

type something that gives 0 results [like hhhhhhhhhhhhhhh] and press enter

**Comment by alyssaxuu** [comment] 2022-01-16 11:31
I've been looking into this and honestly I haven't found a solution. I see on Telegram it requires pressing the Esc key two times to work, it can certainly be a bit annoying. Unsure if I can do anything about it, I considered making the Esc key an "official" command, but if you had an extension that was also using it that would cause issues. Would be interested to see if anyone knows how this could work - I'm assuming it's due to some event.stopPropagation() call?

**Comment by 5R33CH4** [comment] 2022-01-16 12:39
> I've been looking into this and honestly I haven't found a solution. I see on Telegram it requires pressing the Esc key two times to work, it can certainly be a bit annoying. Unsure if I can do anything about it, I considered making the Esc key an "official" command, but if you had an extension that was also using it that would cause issues. Would be interested to see if anyone knows how this could work - I'm assuming it's due to some event.stopPropagation() call?

Is making an `close Omni` fine?

**Comment by sreechar** [comment] 2022-01-16 12:44
> I've been looking into this and honestly I haven't found a solution. I see on Telegram it requires pressing the Esc key two times to work, it can certainly be a bit annoying. Unsure if I can do anything about it, I considered making the Esc key an "official" command, but if you had an extension that was also using it that would cause issues. Would be interested to see if anyone knows how this could work - I'm assuming it's due to some event.stopPropagation() call?

making an `close Omni` command will do right?

**Comment by alyssaxuu** [comment] 2022-01-16 12:45
> > I've been looking into this and honestly I haven't found a solution. I see on Telegram it requires pressing the Esc key two times to work, it can certainly be a bit annoying. Unsure if I can do anything about it, I considered making the Esc key an "official" command, but if you had an extension that was also using it that would cause issues. Would be interested to see if anyone knows how this could work - I'm assuming it's due to some event.stopPropagation() call?
> 
> making an `close Omni` command will do right?

Yes, closeOmni() makes the omnisearch close, the problem is how to make it trigger on the Esc key when Telegram seems to prevent it from propagating.

**Comment by sreechar** [comment] 2022-01-16 13:11
Wont making an action `close Omni` that will call closeOmni() be acceptable?

**Comment by sreechar** [comment] 2022-01-16 13:12
Or better, why not inject `overide-hotkeys.js` to the webpage while initiating omni ?

**Comment by alyssaxuu** [comment] 2022-01-16 13:21
> Wont making an action `close Omni` that will call closeOmni() be acceptable?

No, there are many ways to close Omni already (clicking outside the omnisearch, pressing Esc, and pressing on the extension icon), and they all should work. 

> Or better, why not inject `overide-hotkeys.js` to the webpage while initiating omni ?

This wouldn't solve anything, the keypress event would still not propagate.

**Comment by sreechar** [comment] 2022-01-16 13:21
`overide-hotkeys.js`
```js
onkeydown = function(e){
  if(e.escKey.charCodeAt(0)){
    e.preventDefault();
  }
}
```
ig this would work

**Comment by alyssaxuu** [comment] 2022-01-16 13:44
> ```js
> onkeydown = function(e){
>   if(e.escKey.charCodeAt(0)){
>     e.preventDefault();
>   }
> }
> ```

Doesn't quite work, I ended up doing a different thing though and managed to fix it. A bit weird but basically listening for the keyup event outside jQuery did work, so I used that and then closed it through there.

**Closed by alyssaxuu** 2022-01-16 13:44 UTC
Labels: help wanted
