### ISSUE TITLE
Bug - Many actions open the history page instead of performing requested action 

### ISSUE THREAD

**Issue by MCautreels** [alyssaxuu/omni#11] opened 2022-01-13 09:23 UTC
First of all, great plugin! I'm sure this is going to save me lots of time!

I noticed this issue when trying to use Omni to pin or unpin a tab. It opened the history page instead. I started debugging a bit and noticed that when Omni retrieves the available actions for the following list the "action" attribute is set to "history":
- Bookmark
- Pin tab
- Mute tab
- Help
- Compose email
- New Notion page
- New Sheets spreadsheet
- New Docs document
- New Slides presentation
- New form
- New Medium story
- New GitHub repository
- New GitHub gist
- New CodePen pen
- New Excel spreadsheet
- New PowerPoint presentation
- New Word document
- Create a whiteboard
- Record a video
- Create a Figma file
- Create a FigJam file
- Hunt a product
- Make a tweet
- Create a playlist
- Create a Canva design
- Create a new podcast episode
- Edit an image
- Convert to PDF
- Scan a QR code
- Add a task to Asana
- Add an issue to Linear
- Add a task to WIP
- Create an event
- Add a note
- New meeting
- Browsing history
- Incognito mode
- Extensions
- Scroll to bottom
- Scroll to top
- Go back
- Go forward
- Duplicate tab
- Close tab
- Close window
- Manage browsing data
- Clear all browsing data
- Clear browsing history
- Clear cookies
- Clear cache
- Clear local storage
- Clear passwords

I've tried to dive deeper into the clearActions() function but didn't manage to find the actual problem. 

**Steps to reproduce**

1. Open any webpage
2. Trigger Omni to open (I was using the keyboard shortcut I configured: Ctrl + Shift + K)
3. Select one of the actions from the list above

**Expected result**
The chosen action is executed

**Actual result**
The browser history page (chrome://history) is opened

**System Info**
OS: Chrome OS
Version: 96.0.4664.111 (Official Build) (64-bit)
Extension version: 1.1.3

**Comment by alyssaxuu** [comment] 2022-01-13 10:57
That is odd. I cannot reproduce. I've tried it in all pages, scrolling through the list and searching, clicking and pressing enter, but it worked fine for me in every case. Could be a Chrome OS thing, since I am using the same version from the Chrome Store, or a Chrome versioning issue (I have the 97.0.4692.71). No other users have reported this issue either.

Alternatively, maybe you have some conflicting extension? Really strange nonetheless.

**Comment by 1NFR4R3D** [comment] 2022-01-13 11:32
I can reproduce the issue on my PC
OS - Windows
Browser - Brave Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (64-bit)
Extension ver. - 1.1.3

I also have OneTab and Bitwarden extensions installed; I don't think they would cause issues, though.

**Comment by alyssaxuu** [comment] 2022-01-13 12:02
> 

Did you install it through the Chrome Store? I just downloaded Brave to try to use Omni but it just says "Not compatible". So maybe that's the issue. Could look into porting it though.

**Comment by velkovslav** [comment] 2022-01-13 12:42
This is a really great plugin, I have noticed the same problem on the Edge browser when I click any kind of command it redirects me to the history page

**Comment by alyssaxuu** [comment] 2022-01-13 12:57
> This is a really great plugin, I have noticed the same problem on the Edge browser when I click any kind of command it redirects me to the history page

So odd! I just installed Edge and it worked perfectly fine... Really confused as to what's going on :/ Does this happen right at the moment of install, opening the omnisearch and then selecting any action? Or have you done something specific before trying to perform an action? I've just been trying all sorts of things, searching for /history beforehand, using arrow keys, enter, clicking... Still can't reproduce.

**Comment by Archonz-crazy** [comment] 2022-01-13 14:31
Same thing is happening....I installed through Github and set the shortcut as CTRL+K. Latest update of Chrome on Windows 10.

**Comment by ArditBaloku** [comment] 2022-01-13 14:36
Same problem here, happening on chrome version 97.0.4692.71 on windows 11. Extension version is 1.1.4

**Comment by alyssaxuu** [comment] 2022-01-13 14:39
Oops. Was a missing "=" that was causing issues for non Mac users (so I couldn't reproduce). Fixed now in version 1.1.5, will be live in the Chrome store in up to an hour.

**Closed by alyssaxuu** 2022-01-13 14:39 UTC
Labels: question

**Comment by MCautreels** [comment] 2022-01-13 15:44
Awesome it's indeed fixed and super fast!

**Comment by Archonz-crazy** [comment] 2022-01-13 15:46
Amazing. This is the fastest bug fix I have ever seen!!!
