### ISSUE TITLE
Shortcut commads are not working in fresh tabs

### ISSUE THREAD

**Issue by dolwindavis** [alyssaxuu/omni#28] opened 2022-01-15 05:32 UTC
ctrl + k shortcut is not working when the browser is in a fresh new tab.

**Comment by alyssaxuu** [comment] 2022-01-15 08:58
Duplicate of #21. Sadly Chrome Extensions cannot be injected in the new tab :(

**Closed by alyssaxuu** 2022-01-15 08:58 UTC

**Comment by alyssaxuu** [comment] 2022-01-16 14:49
I've done a workaround and it should be working now.
